# This is a basic workflow to help you get started with Actions

name: Deploy xPollinate Mainnet (staging) via SSH

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploySSH:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Build WebApp
        run: yarn build:xpollinate:staging

      - name: Copy xPollinate Icons
        run: cp ./public/xpollinate/* ./build/

      # Runs a set of commands using the runners shell
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@c711f2c3391cac2876bf4c833590077f02e4bcb8 # easingthemes/ssh-deploy@v2.2.11
        with:
          # Private Key
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # Remote host
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # Remote user
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          # Remote port
          #REMOTE_PORT: # optional, default is 22
          # Source directory
          SOURCE: "build/" # optional, default is
          # Target directory
          TARGET: ${{ secrets.REMOTE_TARGET }}/test/connext # optional, default is /home/REMOTE_USER/
          # Arguments to pass to rsync
          #ARGS: # optional, default is -rltgoDzvO
          # An array of folder to exclude
          #EXCLUDE: # optional, default is

      # Purge Cloudflare caches (https://github.com/marketplace/actions/cloudflare-purge-cache)
      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_ONE }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
          PURGE_URLS: '["https://staging-connext.li.finance/", "https://staging.xpollinate.io"]'

      # Notify Rollbar about release
      - name: Notify deploy to Rollbar
        uses: rollbar/github-deploy-action@2.1.1
        id: rollbar_deploy
        with:
          environment: 'xpollinate-mainnet-staging'
          version: ${{ github.sha }}
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
